name: Test modified scripts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-test-scripts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout generator repository
        uses: actions/checkout@v1
      - name: Test modified and new scripts
        run: |
          for item in `git diff --name-only main..HEAD | grep \.sh$` | grep ^scripts\/
          do
            chmod +x $item
            bash $item
          done
